### Get all notes
GET http://localhost:5001/notes
###

### Get a specific note by ID
GET http://localhost:5001/notes/1
###

### Create a new note
POST http://localhost:5001/notes
Content-Type: application/json

{
    "name": "abbiyu",
    "notes": "Farras Kontol",
    "mood": "Marah"
}
###
PATCH  http://localhost:5001/notes/1
Content-Type: application/json

{
    "name": "abbiyu",
    "notes": "Farras Ksabar",
    "mood": "Marah"
}
###
DELETE   http://localhost:5001/notes/2